name: 'lstm_fomaml'
model_module_name: 'models.lstm_maml'
model_class_name: 'LSTMMAML'

n_train: !!int 60000
n_decay: !!int 10000
print_every_n: !!int 1000
val_every_n: !!float 1000
n_val: !!int 600
n_test: !!int 600
n_samples: !!int 20

lr: !!float 1e-1
meta_lr: !!float 1e-3
patience_iters: !!int 5
n_update: !!int 3
max_grad_norm: !!int 5
batch_size: !!int 5
embedding_size: !!int 250
n_layers: !!int 1
hidden_size: !!int 200
stop_grad: !!bool true
