name: 'lstm_seq2seq'
model_module_name: 'models.lstm_enc_dec'
model_class_name: 'LSTMEncDec'

n_train: !!int 60000
print_every_n: !!int 100
val_every_n: !!float 1000
n_val: !!int 600
n_test: !!int 600
n_samples: !!int 20

lr: !!float 1e-3
patience_iters: !!int 7
max_grad_norm: !!int 5
batch_size: !!int 5
embedding_size: !!int 200
n_layers: !!int 1
hidden_size: !!int 200

stop_grad: !!bool true

enc_size: !!int 32
use_sentinel: !!bool false
use_film: !!bool false
decode_support: !!bool false
